var lunchList = {
  0: "",
  1: "",
  2: "",
  3: "",
  4: "",
  5: "",
  6: "",
  7: "",
  8: "",
  9: "Boneless Chicken Bites",
  10: "Biscuit and Gravy",
  11: "Cheesy Baked Potato",
  12: "Salisbury Steak with Brown Rice",
  13: "Orange Chicken",
  14: "N/A",
  15: "N/A",
  16: "Happy MLK day!",
  17: "Pizza (I think)",
  18: "Chicken & Vegetable Potsticks",
  19: "Chicken & Waffles",
  20: "Beef & Queso Nachos",
  21: "N/A",
  22: "N/A",
  23: "Boneless Chicken Bites",
  24: "Biscuit and Gravy",
  25: "Cheesy Baked Potato",
  26: "Salisbury Steak with Brown Rice",
  27: "Orange Chicken",
  28: "N/A",
  29: "N/A",
  30: "Cheeseburger",
  31: "Texas Toast Grilled Cheese + Tomato Basil Soup",
  32: "Waiting for next months menu!"
}
console.log("Test")
